version: '3.8'

services:

  app:
    container_name: my_project_app
    build: ./
    depends_on:
      - db
    volumes:
      - ./app:/src/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
  db:
    container_name: my_project_postgeres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data/
    restart: always
