version: "3.7"
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db

volumes:
  database: